[en]
  languageName = "English"
  languageCode = "en"
  weight = 1
  title = "Roi Mor | Blog"
  [en.params]
    tagline = "Everything that's on my mind"

[he]
  languageName = "עברית"
  languageCode = "he"
  weight = 2
  title = "רועי מור | בלוג"
  [he.params]
    tagline = "כל מה שעל דעתי"